services:
  epic_events:
    container_name: epic_events
    tty: true
    volumes:
      - type: bind
        source: ./app
        target: /home/user/app
    build:
      context: .
      dockerfile: Dockerfile

  db:
    image: postgres:15
    container_name: epic_events_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: epic_events
    volumes:
      - app-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "5050:80"
    restart: unless-stopped


volumes:
  app-db-data:
