"""Ajout d'un user_id pour les events

Revision ID: 55fb8f533401
Revises: a132ea576c93
Create Date: 2024-09-14 10:38:40.016290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "55fb8f533401"
down_revision: Union[str, None] = "a132ea576c93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("event", sa.Column("user_id", sa.Integer(), nullable=False, server_default="1"))
    op.create_foreign_key(None, "event", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "event", type_="foreignkey")
    op.drop_column("event", "user_id")
    # ### end Alembic commands ###
